apiVersion: apps/v1
kind: Deployment

metadata:
  name: user-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: user-app
          image: user-app:latest  # Must match your local image
          imagePullPolicy: Never  # Forces Kubernetes to use local image
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/userdb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: user-app-service
spec:
  type: NodePort
  selector:
    app: user-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
